package hibernate;
// Generated 16/11/2020 23:09:46 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * AlunoHasTurma generated by hbm2java
 */
public class AlunoHasTurma  implements java.io.Serializable {


     private AlunoHasTurmaId id;
     private BigDecimal AV1;
     private BigDecimal APS_1;
     private BigDecimal AV2;
     private BigDecimal APS_2;
     private BigDecimal AV3;

    public AlunoHasTurma() {
    }

	
    public AlunoHasTurma(AlunoHasTurmaId id) {
        this.id = id;
    }
    public AlunoHasTurma(AlunoHasTurmaId id, BigDecimal av1, BigDecimal aps1, BigDecimal av2, BigDecimal aps2, BigDecimal av3) {
       this.id = id;
       this.AV1 = av1;
       this.APS_1 = aps1;
       this.AV2 = av2;
       this.APS_2 = aps2;
       this.AV3 = av3;
    }
   
    public AlunoHasTurmaId getId() {
        return this.id;
    }
    
    public void setId(AlunoHasTurmaId id) {
        this.id = id;
    }
    public BigDecimal getAv1() {
        return this.AV1;
    }
    
    public void setAv1(BigDecimal av1) {
        this.AV1 = av1;
    }
    public BigDecimal getAps1() {
        return this.APS_1;
    }
    
    public void setAps1(BigDecimal aps1) {
        this.APS_1 = aps1;
    }
    public BigDecimal getAv2() {
        return this.AV2;
    }
    
    public void setAv2(BigDecimal av2) {
        this.AV2 = av2;
    }
    public BigDecimal getAps2() {
        return this.APS_2;
    }
    
    public void setAps2(BigDecimal aps2) {
        this.APS_2 = aps2;
    }
    public BigDecimal getAv3() {
        return this.AV3;
    }
    
    public void setAv3(BigDecimal av3) {
        this.AV3 = av3;
    }




}


