package hibernate;
// Generated 16/11/2020 23:09:46 by Hibernate Tools 4.3.1



/**
 * Aluno generated by hbm2java
 */
public class Aluno  implements java.io.Serializable {


     private Integer idaluno;
     private String nome;
     private String matricula;
     private String senha;

    public Aluno() {
    }

	
    public Aluno(String matricula) {
        this.matricula = matricula;
    }
    public Aluno(String nome, String matricula, String senha) {
       this.nome = nome;
       this.matricula = matricula;
       this.senha = senha;
    }
   
    public Integer getIdaluno() {
        return this.idaluno;
    }
    
    public void setIdaluno(Integer idaluno) {
        this.idaluno = idaluno;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }




}


