package hibernate;
// Generated 16/11/2020 23:09:46 by Hibernate Tools 4.3.1



/**
 * AlunoHasTurmaId generated by hbm2java
 */
public class AlunoHasTurmaId  implements java.io.Serializable {


     private int alunoIdaluno;
     private int turmaMateriaIdmateria;
     private int turmaProfessorIdprofessor;

    public AlunoHasTurmaId() {
    }

    public AlunoHasTurmaId(int alunoIdaluno, int turmaMateriaIdmateria, int turmaProfessorIdprofessor) {
       this.alunoIdaluno = alunoIdaluno;
       this.turmaMateriaIdmateria = turmaMateriaIdmateria;
       this.turmaProfessorIdprofessor = turmaProfessorIdprofessor;
    }
   
    public int getAlunoIdaluno() {
        return this.alunoIdaluno;
    }
    
    public void setAlunoIdaluno(int alunoIdaluno) {
        this.alunoIdaluno = alunoIdaluno;
    }
    public int getTurmaMateriaIdmateria() {
        return this.turmaMateriaIdmateria;
    }
    
    public void setTurmaMateriaIdmateria(int turmaMateriaIdmateria) {
        this.turmaMateriaIdmateria = turmaMateriaIdmateria;
    }
    public int getTurmaProfessorIdprofessor() {
        return this.turmaProfessorIdprofessor;
    }
    
    public void setTurmaProfessorIdprofessor(int turmaProfessorIdprofessor) {
        this.turmaProfessorIdprofessor = turmaProfessorIdprofessor;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AlunoHasTurmaId) ) return false;
		 AlunoHasTurmaId castOther = ( AlunoHasTurmaId ) other; 
         
		 return (this.getAlunoIdaluno()==castOther.getAlunoIdaluno())
 && (this.getTurmaMateriaIdmateria()==castOther.getTurmaMateriaIdmateria())
 && (this.getTurmaProfessorIdprofessor()==castOther.getTurmaProfessorIdprofessor());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAlunoIdaluno();
         result = 37 * result + this.getTurmaMateriaIdmateria();
         result = 37 * result + this.getTurmaProfessorIdprofessor();
         return result;
   }   


}


