package hibernate;
// Generated 16/11/2020 23:09:46 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * AlunoHasTurma generated by hbm2java
 */
public class AlunoHasTurma  implements java.io.Serializable {


     private AlunoHasTurmaId id;
     private BigDecimal av1;
     private BigDecimal aps1;
     private BigDecimal av2;
     private BigDecimal aps2;
     private BigDecimal av3;

    public AlunoHasTurma() {
    }

	
    public AlunoHasTurma(AlunoHasTurmaId id) {
        this.id = id;
    }
    public AlunoHasTurma(AlunoHasTurmaId id, BigDecimal av1, BigDecimal aps1, BigDecimal av2, BigDecimal aps2, BigDecimal av3) {
       this.id = id;
       this.av1 = av1;
       this.aps1 = aps1;
       this.av2 = av2;
       this.aps2 = aps2;
       this.av3 = av3;
    }
   
    public AlunoHasTurmaId getId() {
        return this.id;
    }
    
    public void setId(AlunoHasTurmaId id) {
        this.id = id;
    }
    public BigDecimal getAv1() {
        return this.av1;
    }
    
    public void setAv1(BigDecimal av1) {
        this.av1 = av1;
    }
    public BigDecimal getAps1() {
        return this.aps1;
    }
    
    public void setAps1(BigDecimal aps1) {
        this.aps1 = aps1;
    }
    public BigDecimal getAv2() {
        return this.av2;
    }
    
    public void setAv2(BigDecimal av2) {
        this.av2 = av2;
    }
    public BigDecimal getAps2() {
        return this.aps2;
    }
    
    public void setAps2(BigDecimal aps2) {
        this.aps2 = aps2;
    }
    public BigDecimal getAv3() {
        return this.av3;
    }
    
    public void setAv3(BigDecimal av3) {
        this.av3 = av3;
    }




}


