package hibernate;
// Generated 16/11/2020 23:09:46 by Hibernate Tools 4.3.1



/**
 * Materia generated by hbm2java
 */
public class Materia  implements java.io.Serializable {


     private Integer idmateria;
     private String nome;

    public Materia() {
    }

    public Materia(String nome) {
       this.nome = nome;
    }
   
    public Integer getIdmateria() {
        return this.idmateria;
    }
    
    public void setIdmateria(Integer idmateria) {
        this.idmateria = idmateria;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }




}


