package hibernate;
// Generated 16/11/2020 23:09:46 by Hibernate Tools 4.3.1



/**
 * Professor generated by hbm2java
 */
public class Professor  implements java.io.Serializable {


     private Integer idprofessor;
     private String matricula;
     private String nome;
     private String senha;

    public Professor() {
    }

	
    public Professor(String matricula) {
        this.matricula = matricula;
    }
    public Professor(String matricula, String nome, String senha) {
       this.matricula = matricula;
       this.nome = nome;
       this.senha = senha;
    }
   
    public Integer getIdprofessor() {
        return this.idprofessor;
    }
    
    public void setIdprofessor(Integer idprofessor) {
        this.idprofessor = idprofessor;
    }
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }




}


