package hibernate;
// Generated 16/11/2020 23:09:46 by Hibernate Tools 4.3.1



/**
 * TurmaId generated by hbm2java
 */
public class TurmaId  implements java.io.Serializable {


     private int materiaIdmateria;
     private int professorIdprofessor;

    public TurmaId() {
    }

    public TurmaId(int materiaIdmateria, int professorIdprofessor) {
       this.materiaIdmateria = materiaIdmateria;
       this.professorIdprofessor = professorIdprofessor;
    }
   
    public int getMateriaIdmateria() {
        return this.materiaIdmateria;
    }
    
    public void setMateriaIdmateria(int materiaIdmateria) {
        this.materiaIdmateria = materiaIdmateria;
    }
    public int getProfessorIdprofessor() {
        return this.professorIdprofessor;
    }
    
    public void setProfessorIdprofessor(int professorIdprofessor) {
        this.professorIdprofessor = professorIdprofessor;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TurmaId) ) return false;
		 TurmaId castOther = ( TurmaId ) other; 
         
		 return (this.getMateriaIdmateria()==castOther.getMateriaIdmateria())
 && (this.getProfessorIdprofessor()==castOther.getProfessorIdprofessor());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMateriaIdmateria();
         result = 37 * result + this.getProfessorIdprofessor();
         return result;
   }   


}


