-- MySQL Script generated by MySQL Workbench
-- Fri Sep 25 17:36:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema av1_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `av1_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `av1_db` ;

-- -----------------------------------------------------
-- Table `av1_db`.`DISCIPLINA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `av1_db`.`DISCIPLINA` (
  `idDISCIPLINA` INT NOT NULL,  
  `DISCIPLINA_NOME` VARCHAR(45) NULL,
  PRIMARY KEY (`idDISCIPLINA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `av1_db`.`CURSO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `av1_db`.`CURSO` (
  `idCURSO` INT NOT NULL,
  `NOME_CURSO` VARCHAR(45) NULL,
  PRIMARY KEY (`idCURSO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `av1_db`.`ALUNO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `av1_db`.`ALUNO` (
  `MATRICULA` INT NOT NULL,
  `ALUNO_NOME` VARCHAR(45) NULL,
  `CURSO_idCURSO` INT NOT NULL,
  PRIMARY KEY (`MATRICULA`, `CURSO_idCURSO`),
  INDEX `fk_ALUNO_CURSO1_idx` (`CURSO_idCURSO` ASC) VISIBLE,
  CONSTRAINT `fk_ALUNO_CURSO1`
    FOREIGN KEY (`CURSO_idCURSO`)
    REFERENCES `av1_db`.`CURSO` (`idCURSO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);



-- -----------------------------------------------------
-- Table `av1_db`.`CURSO_has_ALUNO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `av1_db`.`CURSO_has_ALUNO` (
  `CURSO_idCURSO` INT NOT NULL,
  `ALUNO_MATRICULA` INT NOT NULL,
  PRIMARY KEY (`CURSO_idCURSO`, `ALUNO_MATRICULA`),
  INDEX `fk_CURSO_has_ALUNO_ALUNO1_idx` (`ALUNO_MATRICULA` ASC) VISIBLE,
  INDEX `fk_CURSO_has_ALUNO_CURSO_idx` (`CURSO_idCURSO` ASC) VISIBLE,
  CONSTRAINT `fk_CURSO_has_ALUNO_CURSO`
    FOREIGN KEY (`CURSO_idCURSO`)
    REFERENCES `av1_db`.`CURSO` (`idCURSO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CURSO_has_ALUNO_ALUNO1`
    FOREIGN KEY (`ALUNO_MATRICULA`)
    REFERENCES `av1_db`.`ALUNO` (`MATRICULA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `av1_db`.`ALUNO_has_DISCIPLINA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `av1_db`.`ALUNO_has_DISCIPLINA` (
  `ALUNO_MATRICULA` INT NOT NULL,
  `DISCIPLINA_idDISCIPLINA` INT NOT NULL,
  PRIMARY KEY (`ALUNO_MATRICULA`, `DISCIPLINA_idDISCIPLINA`),
  INDEX `fk_ALUNO_has_DISCIPLINA_DISCIPLINA1_idx` (`DISCIPLINA_idDISCIPLINA` ASC) VISIBLE,
  INDEX `fk_ALUNO_has_DISCIPLINA_ALUNO1_idx` (`ALUNO_MATRICULA` ASC) VISIBLE,
  CONSTRAINT `fk_ALUNO_has_DISCIPLINA_ALUNO1`
    FOREIGN KEY (`ALUNO_MATRICULA`)
    REFERENCES `av1_db`.`ALUNO` (`MATRICULA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALUNO_has_DISCIPLINA_DISCIPLINA1`
    FOREIGN KEY (`DISCIPLINA_idDISCIPLINA`)
    REFERENCES `av1_db`.`DISCIPLINA` (`idDISCIPLINA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `av1_db`.`AVALIACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `av1_db`.`AVALIACAO` (
  `idAVALIACAO` INT NOT NULL,
  `TRABALHO_ACADEMICO_AV1` DOUBLE NULL,
  `APS1` DOUBLE NULL,
  `TRABALHO_ACADEMICO_AV2` DOUBLE NULL,
  `APS2` DOUBLE NULL,
  `TRABALHO_ACADEMICO_AV3` DOUBLE NULL,
  `idMATRICULA` INT NOT NULL,
  `idDISCIPLINA` INT NOT NULL,
  PRIMARY KEY (`idAVALIACAO`),
  CONSTRAINT
    FOREIGN KEY (`idMATRICULA`)
    REFERENCES `av1_db`.`ALUNO` (`MATRICULA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT
    FOREIGN KEY (`idDISCIPLINA`)
    REFERENCES `av1_db`.`DISCIPLINA` (`idDISCIPLINA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `avaliacao_chk_1` CHECK (((`APS1` >= 0.0) and (`APS1` <= 3.0))),
  CONSTRAINT `avaliacao_chk_2` CHECK (((`APS2` >= 0.0) and (`APS2` <= 2.0))),
  CONSTRAINT `avaliacao_chk_3` CHECK (((`TRABALHO_ACADEMICO_AV1` >= 0.0) and (`TRABALHO_ACADEMICO_AV1` <= 7.0))),
  CONSTRAINT `avaliacao_chk_4` CHECK (((`TRABALHO_ACADEMICO_AV2` >= 0.0) and (`TRABALHO_ACADEMICO_AV2` <= 8.0))),
  CONSTRAINT `avaliacao_chk_5` CHECK (((`TRABALHO_ACADEMICO_AV3` >= 0.0) and (`TRABALHO_ACADEMICO_AV3` <= 10.0)))
);
