SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

SHOW WARNINGS;

SET SQL_MODE = '';
DROP USER IF EXISTS DBA;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'DBA' IDENTIFIED BY 'admin';

GRANT SELECT, INSERT, TRIGGER ON TABLE `AV2_DEV_BD`.* TO 'DBA';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `AV2_DEV_BD`.* TO 'DBA';
GRANT ALL ON `AV2_DEV_BD`.* TO 'DBA';
GRANT EXECUTE ON `AV2_DEV_BD`.* TO 'DBA';
SET SQL_MODE = '';
DROP USER IF EXISTS DEV;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'DEV' IDENTIFIED BY 'senha';

GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `AV2_DEV_BD`.* TO 'DEV';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

